// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: faosqglupkffxwthxson

class SupabaseConfig {
  static const String supabaseUrl = 'https://faosqglupkffxwthxson.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhb3NxZ2x1cGtmZnh3dGh4c29uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxMDIzNDEsImV4cCI6MjA3NzY3ODM0MX0.-Dmqyi9US9gBPfgDBmArG7E4IKECszbfKV2XmhcxTJE';
}
